services:
  - type: web
    name: conect-commerce-api
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: "/health"
